#!/usr/bin/env bash
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.."
test_build=$(mktemp -d /tmp/macoblox-tests.XXXXXX)
trap 'rm -rf -- "$test_build"' EXIT
clang -O2 -Wall -Wextra -pthread tests/runtime_helpers_test.c shim/worker_wake.c -o "$test_build/runtime"
"$test_build/runtime"
clang -O2 -Wall -Wextra -pthread tests/dns_concurrency_test.c -o "$test_build/dns-concurrency"
"$test_build/dns-concurrency"
clang -O2 -Wall -Wextra tests/thread_stack_test.c -o "$test_build/thread-stack"
"$test_build/thread-stack"
clang -O2 -Wall -Wextra tests/raw_mouse_test.c -o "$test_build/raw-mouse"
"$test_build/raw-mouse"
clang -O2 -Wall -Wextra -pthread tests/cursor_selection_test.c -o "$test_build/cursor-selection"
"$test_build/cursor-selection"
clang -O2 -Wall -Wextra tests/x_modifier_state_test.c -o "$test_build/x-modifier-state"
"$test_build/x-modifier-state"
clang -O2 -Wall -Wextra tests/gpu_info_test.c -o "$test_build/gpu-info"
"$test_build/gpu-info"
clang -std=c11 -O2 -Wall -Wextra -pthread tests/ui_scale_test.c -o "$test_build/ui-scale"
"$test_build/ui-scale"
clang -O2 -Wall -Wextra -pthread tests/graphics_context_test.c shim/graphics_context.c -o "$test_build/graphics-context"
"$test_build/graphics-context"
clang -O2 -Wall -Wextra tests/gl_profile_test.c shim/graphics_context.c -o "$test_build/gl-profile"
"$test_build/gl-profile"
clang -O2 -Wall -Wextra tests/layer_image_test.c -o "$test_build/layer-image"
"$test_build/layer-image"
clang -O2 -Wall -Wextra tests/shader_compat_test.c shim/shader_compat.c -o "$test_build/shader"
"$test_build/shader"
clang -O2 -Wall -Wextra tests/telemetry_hosts_test.c -o "$test_build/telemetry"
"$test_build/telemetry"
clang -O2 -Wall -Wextra tests/connectx_compat_test.c -o "$test_build/connectx"
"$test_build/connectx"
clang -O2 -Wall -Wextra tests/darling_sparse_map_test.c shim/darling_sparse_map.c shim/darling_sparse_map.S -o "$test_build/sparse-map"
"$test_build/sparse-map"
clang -O2 -Wall -Wextra tests/ulock_compat_test.c -o "$test_build/ulock"
"$test_build/ulock"
PYTHONPATH=launcher python3 -m unittest discover -s tests -p '*_test.py'
